services:
  backend:
    build:
      context: ./BackEnd
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=mydatabase;Username=myuser;Password=mypassword
    depends_on:
      - postgres

  frontend:
    build:
      context: ./TipsOnPoints2
    ports:
      - "4200:4200"

  postgres:
    image: postgres:14  # Versão 14 do Postgres (você pode trocar pela versão que preferir)
    environment:
      POSTGRES_USER: admin      # Define o usuário do banco
      POSTGRES_PASSWORD: admin  # Define a senha do usuário
      POSTGRES_DB: tipsonpoints    # Nome do banco de dados a ser criado
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  # Persiste os dados localmente
    ports:
      - "5432:5432"  # Mapeia a porta 5432 do container para sua máquina

volumes:
  pgdata:
