// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TipsOnPoints2.Models;

#nullable disable

namespace TipsOnPoints2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("TipsOnPoints.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Ca_Id");

                    b.Property<string>("Answer")
                        .HasColumnType("TEXT")
                        .HasColumnName("Ca_Answer");

                    b.Property<int?>("ThemeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Ca_ThemeId");

                    b.HasKey("Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("TipsOnPoints.Models.CardTips", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Ct_Id");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Ct_CardId");

                    b.Property<string>("Tip")
                        .HasColumnType("TEXT")
                        .HasColumnName("Ct_Tip");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("CardTips");
                });

            modelBuilder.Entity("TipsOnPoints.Models.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Th_Id");

                    b.Property<string>("PluralTheme")
                        .HasColumnType("TEXT")
                        .HasColumnName("Th_PluralTheme");

                    b.Property<int>("QtyTips")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Th_QtyTips");

                    b.Property<string>("SingleTheme")
                        .HasColumnType("TEXT")
                        .HasColumnName("Th_SingleTheme");

                    b.HasKey("Id");

                    b.ToTable("Theme");
                });

            modelBuilder.Entity("TipsOnPoints.Models.ThemeComplements", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Tc_Id");

                    b.Property<string>("Complements")
                        .HasColumnType("TEXT")
                        .HasColumnName("Tc_Complements");

                    b.Property<int>("ThemeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Tc_ThemeId");

                    b.HasKey("Id");

                    b.HasIndex("ThemeId");

                    b.ToTable("ThemeComplement");
                });

            modelBuilder.Entity("TipsOnPoints.Models.CardTips", b =>
                {
                    b.HasOne("TipsOnPoints.Models.Card", "Card")
                        .WithMany("CardTips")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("TipsOnPoints.Models.ThemeComplements", b =>
                {
                    b.HasOne("TipsOnPoints.Models.Theme", "Theme")
                        .WithMany("ThemeComplements")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("TipsOnPoints.Models.Card", b =>
                {
                    b.Navigation("CardTips");
                });

            modelBuilder.Entity("TipsOnPoints.Models.Theme", b =>
                {
                    b.Navigation("ThemeComplements");
                });
#pragma warning restore 612, 618
        }
    }
}
